In [1]:
import numpy as np

In [137]:
# Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

How many negative numbers are there?

In [9]:
# apply mask (a < 0) to an np_arry. utlize size attribute of mask
a[a < 0].size
# 4

4

How many positive numbers are there?

In [12]:
# apply mask to np.array and return 
a[a > 0].size
# 5 --> Does not include 0's

5

How many even positive numbers are there?

In [141]:
# combined multiple masks with (*). utilized size for description
a[(a > 0) * (a % 2 == 0)].size
# 3

3

In [142]:
a[(a > 0) * (a % 2 == 0)]

array([ 4, 10, 12])

If you were to add 3 to each data point, how many positive numbers would there be?

In [27]:
# created new np.array with results of a + 3. described size of new array
b = a + 3
b[b > 0].size
# 10

10

If you squared each number, what would the new mean and standard deviation be?

In [37]:
a.mean(), a.std()

(3.0, 8.06225774829855)

In [38]:
(a ** 2).mean(), (a ** 2).std()
# new mean --> 74
# new standard deviation --> 144.0243035046516

(74.0, 144.0243035046516)

In [39]:
a ** 2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [44]:
# subtract the mean of the array from each value. returns np.array
a - a.mean(0)

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

Calculate the z-score for each data point. Recall that the z-score is given by:
z(zscore) -- u(mean) -- o(standard deviation)
z = (x-u) / o

In [45]:
z_scores = (a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [46]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use python's built in functionality/operators to determine the following:
Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [48]:
sum_of_a = sum(a)

55

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [50]:
min_of_a = min(a)
min_of_a

1

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [51]:
max_of_a = max(a)

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [56]:
mean_of_a = sum(a)/len(a)

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [57]:
product = 1
for number in a:
    product *= number

3628800

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [60]:
squares_of_a = [num ** 2 for num in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [62]:
odds_in_a = [num for num in a if num % 2 == 1]

[1, 3, 5, 7, 9]

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [63]:
evens_in_a = [num for num in a if num % 2 == 0]

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [66]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [70]:
b.sum()

33

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [71]:
b.min()

3

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [72]:
b.max()

8

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [73]:
b.mean()

5.5

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [75]:
b.prod()

20160

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [76]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [77]:
b[b % 2 == 1]

array([3, 5, 7])

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [78]:
b[b % 2 == 0]

array([4, 6, 8])

# Exercise 9 - print out the shape of the array b.

In [80]:
print(b.shape)

(2, 3)


# Exercise 10 - transpose the array b.

In [83]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [84]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [85]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [87]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [89]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

# Exercise 1 - Find the min, max, sum, and product of c.

In [90]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

# Exercise 2 - Determine the standard deviation of c.

In [91]:
c.std()

2.581988897471611

# Exercise 3 - Determine the variance of c.

In [92]:
c.var()

6.666666666666667

# Exercise 4 - Print out the shape of the array c

In [94]:
print(c.shape)

(3, 3)


# Exercise 5 - Transpose c and print out transposed result.

In [95]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Exercise 6 - Get the dot product of the array c with c. 

In [101]:
np.dot(c,c)
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [98]:
(c * c.transpose()).sum()

261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [104]:
(c * c.transpose()).prod()

131681894400

## Setup 4

In [118]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
 
d = np.array(d)
d = d.astype(int)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

# Exercise 1 - Find the sine of all the numbers in d

In [121]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

# Exercise 2 - Find the cosine of all the numbers in d

In [122]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

# Exercise 3 - Find the tangent of all the numbers in d

In [123]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

# Exercise 4 - Find all the negative numbers in d

In [124]:
d[d < 0]

array([-90, -30, -45, -45])

# Exercise 5 - Find all the positive numbers in d

In [125]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

# Exercise 6 - Return an array of only the unique numbers in d.

In [127]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

# Exercise 7 - Determine how many unique numbers there are in d.

In [128]:
np.unique(d).size

11

# Exercise 8 - Print out the shape of d.

In [129]:
d.shape

(3, 6)

# Exercise 9 - Transpose and then print out the shape of d.

In [130]:
d.transpose().shape

(6, 3)

# Exercise 10 - Reshape d into an array of 9 x 2

In [131]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type git clone git@github.com:rougier/numpy-100.git - Now do cd numpy-100 on your terminal. - Type git remote remove origin, so you won't accidentally try to push your work to Rougier's repo.

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

Go to https://github.com/new to make a new repo. Name it numpy-100.
DO NOT check any check boxes. We need a blank, empty repo.
Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.
Now do work, add it, commit it, and push it!